### ISSUE TITLE
Function: RandomErasing_vertical() 

### ISSUE THREAD

**Issue by minygd** [OasisYang/Horizontal-Pyramid-Matching#4]
Hello, I find that in HPM, the RandomErasing_vertical function may be one of the key idea in your paper. 
Could you be so kind to provide codes such like that? 

Thx.

**Comment by zwyyy215** [comment]
@minygd Did you solve it？I‘m also confused about it.

**Comment by minygd** [comment]
No, the author is not reply yet.
